#!/bin/bash
mvn clean install assembly:single
java -jar target/ImageCompression-1.0-SNAPSHOT-jar-with-dependencies.jar --compress cactus.jpg
java -jar target/ImageCompression-1.0-SNAPSHOT-jar-with-dependencies.jar --decompress cactus.jpg.svdc
